spring:
  h2:
    console:
      enabled: true

#  jackson:
#    date-format: yyyy/MM/dd HH:mm:ss
#    serialization:
#      write-dates-as-timestamps:  false    
      
server:
  port: 4020
  context-path: /