version: '2'
services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  

  basel-config:
    build: basel-config
    environment:
      - CONFIG_SERVICE_PASSWORD=111    
    ports:
      - 8888:8888
    depends_on:
      - "rabbitmq"

  basel-service-registry:
    build: basel-service-registry
    environment:
      - CONFIG_SERVICE_PASSWORD=111
      - BASEL_CONFIG_HOST=basel-config
      - BASEL_RABBITMQ_HOST=rabbitmq
    links:
      - "basel-config"
      - "rabbitmq"
    depends_on:
      - "basel-config"
    ports:
      - 4000:4000

  basel-gateway:
    build: basel-gateway
    environment:
      - CONFIG_SERVICE_PASSWORD=111
      - JWT_SECRET=123
      - BASEL_CONFIG_HOST=basel-config
      - BASEL_SERVICE_REGISTRY_HOST=basel-service-registry
      - BASEL_RABBITMQ_HOST=rabbitmq
    links:
      - "basel-config"
      - "basel-service-registry"
      - "rabbitmq"
    depends_on:
      - "basel-config"
      - "basel-service-registry"
      - "rabbitmq"
    ports:
      - 4010:4010

  basel-integration-gateway:
    build: basel-integration-gateway
    environment:
      - CONFIG_SERVICE_PASSWORD=111
      - BASEL_CONFIG_HOST=basel-config
      - BASEL_SERVICE_REGISTRY_HOST=basel-service-registry
      - BASEL_RABBITMQ_HOST=rabbitmq
    links:
      - "basel-config"
      - "basel-service-registry"
      - "rabbitmq"
    depends_on:
      - "basel-config"
      - "basel-service-registry"
      - "rabbitmq"
    ports:
      - 4015:4015

  basel-service-recalculation:
    build: basel-service-recalculation
    environment:
      - CONFIG_SERVICE_PASSWORD=111
      - BASEL_CONFIG_HOST=basel-config
      - BASEL_SERVICE_REGISTRY_HOST=basel-service-registry
      - BASEL_RABBITMQ_HOST=rabbitmq
    links:
      - "basel-config"
      - "basel-service-registry"
      - "rabbitmq"
    depends_on:
      - "basel-config"
      - "basel-service-registry"
    ports:
      - 4020:4020

  basel-service-brd:
    build: basel-service-brd
    environment:
      - CONFIG_SERVICE_PASSWORD=111
      - BASEL_CONFIG_HOST=basel-config
      - BASEL_SERVICE_REGISTRY_HOST=basel-service-registry
      - BASEL_RABBITMQ_HOST=rabbitmq
    links:
      - "basel-config"
      - "basel-service-registry"
      - "rabbitmq"
    depends_on:
      - "basel-config"
      - "basel-service-registry"
    ports:
      - 4030:4030

  basel-service-monitoring:
    build: basel-service-monitoring
    environment:
      - CONFIG_SERVICE_PASSWORD=111
      - BASEL_CONFIG_HOST=basel-config
      - BASEL_RABBITMQ_HOST=rabbitmq
    links:
      - "basel-config"
      - "rabbitmq"      
    depends_on:
      - "basel-config"          
    ports:
      - 9000:8080
      - 8989:8989