logging:
  level:
    org.springframework.security: INFO

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${BASEL_SERVICE_REGISTRY_HOST:localhost}:4000/eureka/
      